### ISSUE TITLE
FPSLocker does not save fps for games.

### ISSUE THREAD

**Issue by dllroot** [masagrator/FPSLocker#19]
[saltysd_core.log](https://github.com/masagrator/FPSLocker/files/13381592/saltysd_core.log)
[saltysd.log](https://github.com/masagrator/FPSLocker/files/13381595/saltysd.log)

After exiting the game, the fps goes to default .
switch oled

FPSLocker 1.2.5
Status Monitor 1.0.1
EdiZon 1.0.7
Sysmodules 1.2.2-9b.114b3
sys-clk-OC 2023/10/25

CFW 17.0.0|KEF-714-1.6.2|S
hekate 6.0.7

**Comment by masagrator** [comment]
Do you use "save settings" after setting FPS? Sorry for such basic question, but I see nothing helpful here.

**Comment by dllroot** [comment]
Yes) I can only save if I use "convert config to patch file" in those games where it is available.

**Comment by masagrator** [comment]
Fixed

https://github.com/masagrator/FPSLocker/releases/tag/1.2.5a
