### ISSUE TITLE
[Issues] Legend of zelda: BOTW and TOTK patches is not work

### ISSUE THREAD

**Issue by vfa-tuongnt** [masagrator/FPSLocker#22]
I still see the x2 speed after unlocking 60fps even though installing both patches

**Comment by masagrator** [comment]
Read readme. You didn't install patch, you have only downloaded it and put on sdcard. And you must do still one more thing.

**Comment by vfa-tuongnt** [comment]
is it "Convert config to patch file" option?. Sorry if I miss understand, I don't understand how to install patch
