### ISSUE TITLE
Plug-in not applying patch on game boot

### ISSUE THREAD

**Issue by RottedFish** [masagrator/FPSLocker#26]
This is occurring with a number of titles, so I don’t think it’s game specific. FPS Locker is downloading and converting patch files just fine, but it’s failing to apply them on game boot. I’m not sure what, if anything, I may be doing wrong on my end.

**Comment by masagrator** [comment]
Do you have newest FPSLocker and SaltyNX installed?

**Comment by RottedFish** [comment]
Updating SaltySD resulted in the issue being solved.
All good here.
