### ISSUE TITLE
Custom refresh rate for switch's docked output

### ISSUE THREAD

**Issue by AkitoFire** [masagrator/FPSLocker#31]
Seeing how you were able to change the refresh rate for the switch's main display, would it also be possible to change the refresh rate for switch's docked output? 

I have an LG OLED TV that for example accepts both 40 Hz and 50 Hz signals and displays them without skipping frames or judder. Meaning, 40 fps and 50 fps framerate caps in games would look perfect, if the respective refresh rate for the docked output was synced. And 40 and 50 fps are much more attainable and stable than 60 in a lot of games. I also doubt my TV is the only screen where this is possible - 50 Hz for example is a PAL standard after all, and all major TV brands should support that, and most monitors too I think.

**Comment by masagrator** [comment]
It's worked on for some time.

![IMG_20241123_220900](https://github.com/user-attachments/assets/90d7dba2-8f68-469a-a304-06ac1495f6c7)

Don't expect it released before Christmas Eve.

**Comment by Cooler3Ds** [comment]
> And 40 and 50 fps are much more attainable and stable than 60 in a lot of games
It would be a real game changer

**Comment by masagrator** [comment]
Well, Christmas Eve came earlier.
