### ISSUE TITLE
"Config error 0x202" message on the Advance Options menu

### ISSUE THREAD

**Issue by RafaelTrepaUnCarballo** [masagrator/FPSLocker#7]
It doesn't seem to affect the usage of FPSLocker, but what does it mean?

Is the error about the game API info the plugin was supposed to give me?

**Comment by masagrator** [comment]
![Screenshot_2023-04-06-14-09-28-703_com discord-edit](https://user-images.githubusercontent.com/8557858/230374924-32e4c506-699a-4075-b6a8-80abd986790f.jpg)


This means that your version of game doesn't have any config available that can be converted to patch. It's a bug only if there should be a config detected, but it's not. If your version of game is listed on Warehouse as game that has patch available, you did update patches on your sdcard to latest ones and you still have this error, it's probably a bug.
